[package]
name = "seedy_company"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
bevy = "0.10"
bevy_mod_yarn = { git = "https://github.com/kaosat-dev/bevy_mod_yarn" }
